### PR TITLE
Add srcset attribute

### PR DESCRIPTION
**Pull request by Siilwyn**
:wave: hi @feross seems like this attribute is missing from conversion.

btw. I removed the trailing comma but with a trailing comma the git diff would be cleaner.

### CODE REVIEW

**Comment by feross** [comment]
@Siilwyn Thanks for the PR! Can you please share a link to the spec or any page that documents this property? I couldn't confirm that this attribute maps to the property you specified.

**Comment by Siilwyn** [comment]
@feross Hi you're welcome! There is a detailed page on `srcset` at MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset

I got the transformation from `srcset` to `srcSet` by inspecting an image with the browser devtools and seeing `$0.srcSet` gives back the attribute value.

**Comment by feross** [comment]
I just tested with this code:

```js
const img = document.createElement('img')
img.setAttribute('srcset', 'test')
console.log(1, img.srcset)
console.log(2, img.srcSet)
```

which outputs:

```
1 "test"
2 undefined
```

Are you sure that `srcSet` is the correct property name?

**Comment by Siilwyn** [comment]
Ah my bad, this doesn't seem to match up. Now that I'm thinking back at this issue I remember this had something to do with React. :thinking: 
I'll do some digging, perhaps React is just being the odd one for this attribute and it falls outside this project.

**Comment by feross** [comment]
Okay, no problem! I'll close this for now but do let me know if you discover that there's indeed a bug here :)

**Pull request closed without merging**
